# Generated by Django 3.0.3 on 2020-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='healthCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Executed')),
                ('test_id', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=400)),
                ('severity', models.CharField(max_length=50)),
                ('ipaddr', models.GenericIPAddressField()),
                ('hostname', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=400)),
                ('verdict', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=1000)),
            ],
        ),
    ]
