# Generated by Django 3.0.3 on 2020-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_logfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='site',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
