# Generated by Django 3.0.3 on 2020-03-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_healthcheck_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logfile_Testlab1',
            fields=[
                ('logfile', models.FileField(upload_to='testlab1/')),
                ('uploaded_at', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Logfile_Testlab2',
            fields=[
                ('logfile', models.FileField(upload_to='testlab2/')),
                ('uploaded_at', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Logfile',
        ),
    ]
