# Generated by Django 3.0.3 on 2020-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200318_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execute1',
            fields=[
                ('user', models.CharField(blank=True, max_length=50)),
                ('logfile', models.FileField(blank=True, upload_to='execute1/')),
                ('jsonfile', models.FileField(blank=True, upload_to='execute1/')),
                ('timestamp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timestamp_str', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
