# Generated by Django 3.0.3 on 2020-04-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_execute1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execute1',
            name='jsonfile',
        ),
        migrations.RemoveField(
            model_name='execute1',
            name='logfile',
        ),
    ]
