# Generated by Django 3.0.3 on 2020-04-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_failedpositive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ignoreTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=264)),
                ('severity', models.CharField(max_length=50)),
                ('ipaddr', models.GenericIPAddressField()),
                ('hostname', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=264)),
                ('verdict', models.CharField(max_length=264)),
                ('remarks', models.CharField(max_length=1000)),
                ('test_id', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
            ],
        ),
    ]
