# Generated by Django 3.0.3 on 2020-06-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_ignoretest'),
    ]

    operations = [
        migrations.CreateModel(
            name='adhocData',
            fields=[
                ('user', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timestamp_str', models.CharField(max_length=50)),
                ('logfile', models.FileField(upload_to='')),
                ('jsonfile', models.FileField(upload_to='')),
                ('site', models.CharField(max_length=50)),
            ],
        ),
    ]
